#!name=Picsart
#!desc=picsart解锁会员
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/picsart.png
#!homepage=https://github.com/deezertidal
[Script]
Picsart=type=http-response,pattern=^https?:\/\/api\.(meiease|picsart)\.cn\/(users\/show\/me|shop\/subscription\/apple\/purchases) url script-response-body https://raw.githubusercontent.com/yqc007/QuantumultX/master/PicSartProCrack.js

[MITM]
hostname = %APPEND% api.meiease.cn, api.picsart.cn
